import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import { Heading, Box, Flex, Input } from '@chakra-ui/react';
import Episode from '../Components/Episode';
import Character from '../Components/Characters';

export default function Home() {
  const [characters, setCharacters] = useState([]);
  const [episode, setEpisode] = useState([]);
  const [search, setSearch] = useState("");

  return (
    <Flex direction="column" justify="center" align="center">
      <Head>
        <title>NextJs and GraphQL DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box mb={4} flexDirection="column" align="center" justify="center" py={8}>
        <Heading as="h1" size="2x1" mb={8}>
          Rick and Morty Casting List by Roger
        </Heading>
        <Input placeholder="Type Episode Id here"
               type="number"
               min="1"
               width="100%"
               height="50px"
               value={search}
               border="none"
               mb={8}
               onChange={async (event) => {
               event.preventDefault();
                setSearch(event.target.value);
                  const results = await fetch("/api/SearchEpisodeById", {
                    method: "post",
                    body: event.target.value
                  });
                const {episode, characters, error} = await results.json();
                  if (!error) {
                    setEpisode(episode);
                    setCharacters(characters);
                  } else{
                    setEpisode([]);
                    setCharacters([]);
                  }
               }}>
        </Input>
        <Episode episode={episode} />
        <Character characters={characters} />
      </Box>
      <footer className={styles.footer}>
          Roger Law demo 20210626
      </footer>
    </Flex>
  )
}